Document: vyatta-op
Title: Debian vyatta-op Manual
Author: <insert document author here>
Abstract: This manual describes what vyatta-op is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vyatta-op/vyatta-op.sgml.gz

Format: postscript
Files: /usr/share/doc/vyatta-op/vyatta-op.ps.gz

Format: text
Files: /usr/share/doc/vyatta-op/vyatta-op.text.gz

Format: HTML
Index: /usr/share/doc/vyatta-op/html/index.html
Files: /usr/share/doc/vyatta-op/html/*.html

  
