#!/bin/bash
# **** License ****
# Version: VPL 1.0
#
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2007 Vyatta, Inc.
# All Rights Reserved.
#
# Author: Tom Grennan
# Date: 2007
#
# **** End License ****

# TODO add other version info

for cl in /usr/share/doc/vyatta-*/changelog.gz ; do
  dir=${cl%/*} ;
  pkg=${dir##*/} ;
  printf "  %-20s " ${pkg} ;
  test ${#pkg} -lt 20 || echo -ne \\n\\t ;
  gunzip -c $cl | tail -n1 ;
done

###  Local Variables:
###  mode: shell-script
###  End:
