#!/bin/bash

if [ ! -d /sys/class/dmi ]; then
	echo "DMI information not available"
	exit 1
fi

for var in /sys/class/dmi/id/*
do
   tag=$(basename $var)
   if [ -f $var -a -r $var -a $tag != uevent -a $tag != modalias ]; then
	echo -n "$tag: "
	cat $var
   fi
done
