#!/bin/sh

RULE_PATH=$1
RULE_NUM=$2

if ! cli-shell-api existsActive $RULE_PATH rule $RULE_NUM log; then
    echo "Warning: logging is not enabled for rule $RULE_NUM"
    echo "For proper monitor operation enable logging before issuing this command:"
    echo "set $RULE_PATH rule $RULE_NUM log enable"
fi
