#!/bin/bash
declare pidname="$1"
pidfile="/var/run/vyatta/monitor/$pidname-`tty| sed -e s-/--g -e s/dev//g`.pid"
if [ -f $pidfile ]; then
  pid=$(cat $pidfile)
  processname=$(cat /proc/$pid/cmdline 2>/dev/null) 
  if [[ $processname =~ "tail" ]];then
   kill -9 $pid
   rm -f $pidfile
   exit 0
  fi
fi
echo -ne "\n  You are not currently monitoring this service\n\n"  
